version: "3.3"
services:
  web:
    build: .
    image: ghcr.io/romeano-inc/core-app:latest
    ports:
      - "80:3000"
    volumes:
      - uploads:/app/.blitz/build/public/uploads

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  uploads: prod_data/uploads
  pgdata: prod_data/pgdata
