version: "3.3"
services:
  web:
    build: .
    image: ghcr.io/romeano-inc/core-app:latest
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ${PWD}/prod_data/uploads
        target: /app/.blitz/build/public/uploads

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: bind
        source: ${PWD}/prod_data/pgdata
        target: /var/lib/postgresql/data
